name: Build and Publish FRC5010Lib vendordep
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Release version number"
        type: string
        required: true
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      releaseVersion: ${{ inputs.releaseVersion }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Clone dev branch
        run: |
          gh repo clone FRC5010/FRC5010LibExample -- -b dev
      - name: Copy source over
        run: |
          rm -rf src/main/java/org
          cp -r FRC5010LibExample/Example/src/main/java/org src/main/java/
      - name: Copy vendordeps over
        run: |
          rm vendordeps/*
          cp FRC5010LibExample/Example/vendordeps/* vendordeps/
          rm vendordeps/photon*
          rm vendordeps/Pathplanner*
      - name: Removing source repo
        run: |
          rm -rf FRC5010LibExample
      - name: Install roboRio toolchain
        run: ./gradlew installRoboRioToolchain
      - name: Build vendordep
        run: ./gradlew build
      - name: Generate Javadocs
        run: ./gradlew javadoc
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/javadoc
      - name: Publish vendordep
        run: ./gradlew publish
      - name: Update repository
        run: |
          git config --global user.name "clrozeboom"
          git config --global user.email "clrozeboom@users.noreply.github.com"
          git add .
          git commit -m "Upgrading to ${{ inputs.releaseVersion }}"
          git push
